SalaryCalc/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from core.sitemaps import IndexViewSitemap, OtherPageSitemap

sitemaps = {
    'index': IndexViewSitemap,
    'otherpage': OtherPageSitemap,
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    
    path('adm1n/', admin.site.urls),
    path("", include("identity.urls")),
    path("", include("core.urls", namespace="core")),

    # API Rest Framework
    path('api-auth/', include('rest_framework.urls')),

    # API APP
    path("api/", include("core.api.urls", namespace="api_core")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SalaryCalc/core/api/urls.py
from django.urls import path
from . import views as api_views

app_name = "api_core"
urlpatterns = [
    path("subscriber/", api_views.SubscriberCreateAPIView.as_view(),
         name="api_subscriber_create_view"),
]

SalaryCalc/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path("", views.index_view, name="index_view"),
    path("gross-to-nett", views.groos_to_nett_view, name="groos_to_nett_view"),
    path("nett-to-gross", views.nett_to_gross_view, name="nett_to_gross_view"),
    path("work-calendar", views.work_calendar_view, name="work_calendar_view"),
    path("faq", views.faq_view, name="faq_view"),
    path("contact", views.contact_view, name="contact_view"),
]

SalaryCalc/core/forms.py
from django import forms
from datetime import date
from core.models import WorkCalendar
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import (
    Contact,
)


class SalaryCalculationForm(forms.Form):
    GROUP_CHOICES = [
        ('a', 'A'),
        ('b', 'B'),
        ('c', 'C'),
        ('d', 'D'),
        ('g', 'Gündəlik'),
    ]

    try:
        years = WorkCalendar.get_years_list()
        years_min = min(years)
        years_max = max(years)
    except:
        years_min = years_max = date.today().year

    group_name = forms.ChoiceField(
        choices=GROUP_CHOICES,
        widget=forms.RadioSelect(attrs={'class': 'form-check-input'}),
        initial='a',
    )
    year_month = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'month',
            'class': 'form-control',
            'min': f'{years_min}-01',
            'max': f'{years_max}-12'
        }),
        input_formats=['%Y-%m']
    )
    overtime = forms.DecimalField(
        min_value=0,
        max_digits=5,
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=False
    )
    bonus_percent = forms.DecimalField(
        min_value=0,
        max_value=500,
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=False
    )
    monthly_salary = forms.DecimalField(
        min_value=1,
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}),
    )

    def clean_year_month(self):
        year_month = self.cleaned_data['year_month']

        min_value = date(self.years_min, 1, 1)
        max_value = date(self.years_max, 12, 1)

        if not (min_value <= year_month <= max_value):
            raise ValidationError(
                _('İl və ay %(min)s və %(max)s arasında olmalıdır'),
                params={'min': min_value.strftime(
                    '%Y-%m'), 'max': max_value.strftime('%Y-%m')},
            )

        return year_month


class GrossToNettForm(forms.Form):
    gross = forms.DecimalField(
        min_value=1,
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}),
    )
    union_membership_percent = forms.DecimalField(
        min_value=0,
        max_value=20,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=False
    )


class NettToGrossForm(forms.Form):
    nett = forms.DecimalField(
        min_value=1,
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}),
    )


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'subject', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Ad Soyad'}),
            'email': forms.EmailInput(attrs={'class': 'input', 'placeholder': 'E-poçt'}),
            'subject': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Mövzu'}),
            'message': forms.Textarea(attrs={'class': 'input', 'placeholder': 'Mesaj'}),
        }

SalaryCalc/core/api/views.py
from rest_framework import generics
from rest_framework import permissions
from .serializers import SubscriberSerializer
from core.models import Subscriber


class SubscriberCreateAPIView(generics.CreateAPIView):
    queryset = Subscriber.objects.all()
    serializer_class = SubscriberSerializer
    permission_classes = [permissions.AllowAny]

SalaryCalc/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from .utils import (
    calculate_salary,
    calculate_gross_to_nett,
    calculate_nett_to_gross,
)
from .forms import (
    SalaryCalculationForm,
    GrossToNettForm,
    NettToGrossForm,
    ContactForm,
)
from .models import (
    WorkCalendar,
    Month,
    SalaryCalculation,
    FAQ,
    CalculationCount
)


# Create your views here.


@login_required
def index_view(request):
    if request.method == "POST":
        form = SalaryCalculationForm(data=request.POST)
        if form.is_valid():
            group_name = form.cleaned_data["group_name"]
            year_month = form.cleaned_data["year_month"]
            overtime = form.cleaned_data["overtime"] or 0
            bonus_percent = form.cleaned_data["bonus_percent"] or 0
            monthly_salary = form.cleaned_data["monthly_salary"]

            data = calculate_salary(
                group_name, year_month, monthly_salary, overtime, bonus_percent)

            if data:
                try:
                    SalaryCalculation.objects.create(
                        user=request.user,
                        year=data["year"],
                        month=data["month"],
                        shift=data["shift"],
                        salary=data["salary"],
                        overtime=data["overtime"],
                        bonus_percent=data["bonus_percent"],
                        hourly_wage=data["hourly_wage"],
                        night_work_pay=data["night_work_pay"],
                        extra_hour_pay=data["extra_hour_pay"],
                        holiday_hour_pay=data["holiday_hour_pay"],
                        overtime_pay=data["overtime_pay"],
                        bonus_pay=data["bonus_pay"],
                        gross=data["gross"],
                        nett=data["nett"],
                        income_tax=data["income_tax"],
                        dsmf_tax=data["dsmf_tax"],
                        unemployment_insurance_tax=data["unemployment_insurance_tax"],
                        compulsory_health_insurance_tax=data["compulsory_health_insurance_tax"]
                    )

                    calculation_count = CalculationCount.objects.first()
                    if calculation_count:
                        calculation_count.count += 1
                        calculation_count.save()
                    else:
                        CalculationCount.objects.create(count=1)

                    messages.success(request, _(
                        "Maaş hesablama uğurla tamamlandı."))
                    return redirect(reverse_lazy("core:index_view"))
                except Exception as e:
                    print(f"An error occurred: {str(e)}")
                    messages.error(request, _(
                        "Maaş hesablanması zamanı xəta baş verdi. Zəhmət olmasa bir daha cəhd edin."))
                    return redirect(reverse_lazy("core:index_view"))
            else:
                messages.warning(request, _(
                    "Maaş hesablanması zamanı xəta baş verdi. Zəhmət olmasa bir daha cəhd edin. Əgər xəta təkrarlanarsa bizimlə əlaqə saxlayın."))
                print(f"An error occurred: {data}")
                return redirect(reverse_lazy("core:index_view"))
    else:
        form = SalaryCalculationForm()

    user_salary_calculations = SalaryCalculation.objects.filter(
        user=request.user, is_active=True).order_by("-created_at")[:10]

    # Retrieve corresponding WorkCalendar instances for each SalaryCalculation
    for calculation in user_salary_calculations:
        try:
            work_calendar = WorkCalendar.objects.get(
                year=calculation.year,
                month=calculation.month
            )
            calculation.nighttime_work_hour = getattr(
                work_calendar, f"group_{calculation.shift.value}_nighttime_work_hour", 0
            )
            calculation.holiday_work_hour = getattr(
                work_calendar, f"group_{calculation.shift.value}_holiday_work_hour", 0
            )

            monthly_work_hour = getattr(work_calendar, "monthly_work_hour", 0)
            general_work_hour = getattr(work_calendar, f"group_{calculation.shift.value}_general_work_hour", 0)
            calculation.extra_work_hour = max(0, general_work_hour - monthly_work_hour)
        except WorkCalendar.DoesNotExist:
            # Handle the case where WorkCalendar does not exist for the specified year and month
            calculation.nighttime_work_hour = None
            calculation.holiday_work_hour = None
            calculation.extra_work_hour = None
        except Exception as e:
            print(f"An error occurred: {str(e)}")

    context = {
        "form": form,
        "user_salary_calculations": user_salary_calculations
    }
    return render(request, "core/index.html", context)


def groos_to_nett_view(request):
    data = None

    if request.method == "POST":
        form = GrossToNettForm(data=request.POST)
        if form.is_valid():
            gross = form.cleaned_data["gross"]
            union_membership_percent = form.cleaned_data["union_membership_percent"] or 0

            data = calculate_gross_to_nett(
                gross, union_membership_percent=union_membership_percent)

            if data:
                form = GrossToNettForm()

                calculation_count = CalculationCount.objects.first()
                if calculation_count:
                    calculation_count.count += 1
                    calculation_count.save()
                else:
                    CalculationCount.objects.create(count=1)

                messages.success(request, _("Hesablama tamamlandı."))
            else:
                messages.warning(request, _(
                    "Hesablama zamanı xəta baş verdi. Zəhmət olmasa bir daha cəhd edin."))
                return redirect(reverse_lazy("core:groos_to_nett_view"))
    else:
        form = GrossToNettForm()

    context = {
        "form": form,
        "data": data
    }
    return render(request, "core/gross-to-nett.html", context)


def nett_to_gross_view(request):
    data = None

    if request.method == "POST":
        form = NettToGrossForm(data=request.POST)
        if form.is_valid():
            nett = form.cleaned_data["nett"]

            data = calculate_nett_to_gross(nett)

            if data:
                form = NettToGrossForm()

                calculation_count = CalculationCount.objects.first()
                if calculation_count:
                    calculation_count.count += 1
                    calculation_count.save()
                else:
                    CalculationCount.objects.create(count=1)
                                    
                messages.success(request, _("Hesablama tamamlandı."))
            else:
                messages.warning(request, _(
                    "Hesablama zamanı xəta baş verdi. Zəhmət olmasa bir daha cəhd edin."))
                return redirect(reverse_lazy("core:nett_to_gross_view"))
    else:
        form = NettToGrossForm()

    context = {
        "form": form,
        "data": data
    }
    return render(request, "core/nett-to-gross.html", context)


def work_calendar_view(request):
    years = WorkCalendar.get_years_list()
    months = Month.objects.all()
    work_calendar_data = WorkCalendar.get_work_calendar_data()

    context = {
        "years": years,
        "months": months,
        "work_calendar_data": work_calendar_data
    }
    return render(request, "core/work-calendar.html", context)


def faq_view(request):
    faqs = FAQ.objects.filter(is_active=True).order_by("display_order")

    context = {
        "faqs": faqs,
    }
    return render(request, "core/faq.html", context)


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _("Mesaj uğurla göndərildi."))
            return redirect(reverse_lazy("core:contact_view"))
    else:
        form = ContactForm()

    context = {
        "form": form
    }
    return render(request, "core/contact.html", context)

SalaryCalc/core/templates/core/includes/alert-close-message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-check-circle me-2"></i>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-info-circle me-2"></i>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-exclamation-triangle me-2"></i>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-times-circle me-2"></i>
        {% else %}
            <div class="alert alert-info alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-info-circle me-2"></i>
        {% endif %}
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
    {% endfor %}
{% endif %}

SalaryCalc/core/templates/core/includes/alerts.html
{% if alert_messages %}
    {% for alert in alert_messages %}
        {% if alert.type == 'success' %}
            <div class="alert alert-success alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-check-circle me-2"></i>
        {% elif alert.type == 'info' %}
            <div class="alert alert-info alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-info-circle me-2"></i>
        {% elif alert.type == 'warning' %}
            <div class="alert alert-warning alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-exclamation-triangle me-2"></i>
        {% elif alert.type == 'danger' %}
            <div class="alert alert-danger alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-times-circle me-2"></i>
        {% else %}
            <div class="alert alert-secondary alert-dismissible fade show text-center m-0" role="alert">
                <i class="fas fa-info-circle me-2"></i>
        {% endif %}
                <strong>{{ alert.text }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
    {% endfor %}
{% endif %}

SalaryCalc/core/templates/core/includes/footer.html
{% load static %}

<footer>
  <div class="content">
    <div class="top">
      <div class="logo-details">
        <img src="{% static "img/salary-calc-icon.png" %}"
        alt="salary-calc-logo" class="footer-logo" />
        <span class="logo_name">Salary<span>Calc</span></span>
      </div>
      <div class="media-icons">
        {% if site_info_global.facebook_url %}
        <a href="{{ site_info_global.facebook_url }}" class="facebook"><i class="fab fa-facebook-f"></i></a>
        {% endif %}
        {% if site_info_global.github_url %}
        <a href="{{ site_info_global.github_url }}" class="github"><i class="fab fa-github"></i></a>
        {% endif %}
        {% if site_info_global.instagram_url %}
        <a href="{{ site_info_global.instagram_url }}" class="instagram"><i class="fab fa-instagram"></i></a>
        {% endif %}
        {% if site_info_global.linkedin_url %}
        <a href="{{ site_info_global.linkedin_url }}" class="linkedin"><i class="fab fa-linkedin-in"></i></a>
        {% endif %}
        {% if site_info_global.youtube_url %}
        <a href="{{ site_info_global.youtube_url }}" class="youtube"><i class="fab fa-youtube"></i></a>
        {% endif %}
      </div>
      <div class="line-footer"></div>
    </div>

    <div class="link-boxes">
      <ul class="box">
        <li class="link_name">Səhifələr</li>
        <li><a href="{% url "core:index_view" %}">Maaş</a></li>
        <li><a href="{% url "core:groos_to_nett_view" %}">Gross'dan Nett'ə</a></li>
        <li><a href="{% url "core:nett_to_gross_view" %}">Nett'dən Gross'a</a></li>
      </ul>
      <ul class="box">
        <li class="link_name">Səhifələr</li>
        <li><a href="{% url "core:contact_view" %}">Əlaqə</a></li>
        <li><a href="{% url "core:faq_view" %}">Tez-tez verilən suallar</a></li>
        <li><a href="{% url "core:work_calendar_view" %}">İstehsalat Təqvimi</a></li>
      </ul>
      <ul class="box input-box">
        <li class="link_name">Abunə ol</li>
        <form id="subscribe-form" method="post">
          {% csrf_token %}
          <li><input type="email" name="email" id="subscribe-email" placeholder="Elektron ünvanı qeyd et" /></li>
          <ul class="errorlist"></ul>
          <li><input type="submit" value="Abunə ol" /></li>
        </form>
      </ul>
    </div>
  </div>
  <div class="bottom-details">
    <div class="bottom_text">
      <span class="copyright_text"
        >Copyright &#169; 2023 <a href="#">SalaryCalc.</a>Bütün hüquqları
        qorunur</span
      >
      <span class="policy_terms">
        <a href="{% if site_info_global.privacy_policy_url %}{{ site_info_global.privacy_policy_url }}{% else %}#{% endif %}">Gizlilik siyasəti</a>
        <a href="{% if site_info_global.terms_condition_url %}{{ site_info_global.terms_condition_url }}{% else %}#{% endif %}">Şərtlər & qaydalar</a>
      </span>
    </div>
  </div>
</footer>

SalaryCalc/core/templates/core/includes/header.html
{% load static %}

<div class="overlay"></div>
<header class="header-area">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-3">
        <div class="brand">
          <a href="{% url "core:index_view" %}" class="logo">
            <img src="{% static "img/salary-calc-icon.png" %}"
            alt="salary-calc-logo" />
          </a>
        </div>
      </div>
      <div class="col-9 d-flex align-items-center justify-content-flex-end">
        <div class="open-nav-menu">
          <span></span>
        </div>
        <div class="main-menu">
          <nav>
            <div class="close-nav-btn"></div>
            <ul>
              <li class="menu-item menu-has-child-item">
                <a data-toggle="sub-menu" class="sub-menu-title">Hesablama</a>
                <ul class="submenu">
                  <li class="menu-item">
                    <a href="{% url "core:index_view" %}" class="{% if request.resolver_match.view_name == 'core:index_view' %}active{% endif %}">Maaş</a>
                  </li>
                  <li class="menu-item">
                    <a href="{% url "core:groos_to_nett_view" %}" class="{% if request.resolver_match.view_name == 'core:groos_to_nett_view' %}active{% endif %}">Gross'dan Nett'ə</a>
                  </li>
                  <li class="menu-item">
                    <a href="{% url "core:nett_to_gross_view" %}" class="{% if request.resolver_match.view_name == 'core:nett_to_gross_view' %}active{% endif %}">Nett'dən Gross'a</a>
                  </li>
                </ul>
              </li>
              <li class="menu-item menu-has-child-item">
                <a data-toggle="sub-menu" class="sub-menu-title">Əlavə Məlumat</a>
                <ul class="submenu">
                  <li class="menu-item">
                    <a href="{% url "core:work_calendar_view" %}" class="{% if request.resolver_match.view_name == 'core:work_calendar_view' %}active{% endif %}">İstehsalat təqvimi</a>
                  </li>
                  <li class="menu-item">
                    <a href="{% url "core:faq_view" %}" class="{% if request.resolver_match.view_name == 'core:faq_view' %}active{% endif %}">Tez-tez verilən suallar</a>
                  </li>
                </ul>
              </li>
              <li class="menu-item"><a href="{% url "core:contact_view" %}" class="{% if request.resolver_match.view_name == 'core:contact_view' %}active{% endif %}">Əlaqə</a></li>

              {% if not request.user.is_authenticated %}
                <li class="menu-item">
                  <a class="btn btn-primary px-4 login-btn {% if request.resolver_match.view_name == 'core:index_view' %}active{% endif %}" href="{% url "account_login" %}"
                    >Giriş</a
                  >
                </li>
              {% else %}
                <li class="menu-item menu-has-child-item">
                  <a data-toggle="sub-menu" class="sub-menu-title">{{ request.user.username }}</a>
                  <ul class="submenu">
                    <li class="menu-item"><a 
                      href="{% url "profile_view" %}"
                      class="{% if request.resolver_match.view_name == 'profile_view' or request.resolver_match.view_name == 'account_change_password' %}active{% endif %}"
                      >
                      Hesab
                      </a>
                    </li>
                    <li class="menu-item"><a href="{% url 'account_logout' %}">Çıxış</a></li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>